# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jemoji

# Site settings
author: Jackson Polatnick
email: jacksonpolatnick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" #"/thoughts" # the subpath of your site, e.g. /blog

title: Jackson William
url: "http://jpolatnick.github.io"
imgurl: "http://jpolatnick.github.io/img"

# list of links in navbar
# navbar-links:
  # About: "about"
  # Projects: "projects"
  

github_username:  jpolatnick
twitter_username: jpolatnick

footer_links:
  linkedin: jackson-polatnick-1b0a11b0/

social-network-links:
  linkedin: https://www.linkedin.com/in/jackson-polatnick-1b0a11b0/
  twitter: https://twitter.com/sachaker

share-links-active:
  linkedin: true
  twitter: true
excerpt_separator: <!--exc-->

# Build settings
markdown: kramdown
